# Generated by Django 5.1.3 on 2024-12-02 16:36

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("reopt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rundata",
            name="battery_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rundata",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="rundata",
            name="country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="rundata",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rundata",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rundata",
            name="pv_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rundata",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="rundata",
            name="name",
            field=models.CharField(
                blank=True, default="", max_length=200, null=True
            ),
        ),
        migrations.CreateModel(
            name="RunMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "webtool_uuid",
                    models.TextField(blank=True, default="", editable=False),
                ),
                (
                    "user_uuid",
                    models.TextField(blank=True, default="", editable=False),
                ),
                (
                    "portfolio_uuid",
                    models.TextField(blank=True, default="", editable=False),
                ),
                (
                    "run_uuid",
                    models.TextField(blank=True, default="", editable=False),
                ),
                ("api_version", models.CharField(blank=True, null=True)),
                ("reoptjl_version", models.CharField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("optimal", "Optimal"), ("error", "Error")],
                        max_length=200,
                        null=True,
                    ),
                ),
                ("direct_reoptjl", models.BooleanField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "run_data",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runmeta",
                        to="reopt.rundata",
                    ),
                ),
            ],
        ),
    ]
