# Generated by Django 5.1.3 on 2025-01-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reopt",
            "0002_rundata_battery_size_rundata_city_rundata_country_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="rundata",
            old_name="battery_size",
            new_name="battery_energy_size",
        ),
        migrations.RenameField(
            model_name="runmeta",
            old_name="run_uuid",
            new_name="api_run_uuid",
        ),
        migrations.RenameField(
            model_name="runmeta",
            old_name="portfolio_uuid",
            new_name="webtool_portfolio_uuid",
        ),
        migrations.RenameField(
            model_name="runmeta",
            old_name="user_uuid",
            new_name="webtool_user_uuid",
        ),
        migrations.RemoveField(
            model_name="runmeta",
            name="api_version",
        ),
        migrations.RemoveField(
            model_name="runmeta",
            name="webtool_uuid",
        ),
        migrations.AddField(
            model_name="rundata",
            name="battery_power_size",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="runmeta",
            name="webtool_run",
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
    ]
