# Generated by Django 5.1.3 on 2025-02-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reopt", "0004_alter_runmeta_webtool_run"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runmeta",
            name="api_run_uuid",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="runmeta",
            name="webtool_portfolio_uuid",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="runmeta",
            name="webtool_run",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="runmeta",
            name="webtool_user_uuid",
            field=models.TextField(blank=True, default=""),
        ),
    ]
