# Generated by Django 5.1.3 on 2025-02-04 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reopt", "0005_alter_runmeta_api_run_uuid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="runmeta",
            name="direct_api_run",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
